name: Ubuntu 20.04 continuous test suite

on:
  push:
    branches:
      - develop

jobs:

  build-and-test:

    name: Test on Ubuntu 20.04
    runs-on: ubuntu-20.04
    env:
      CHASTE_TEST_OUTPUT: ${{ github.workspace }}/chaste-test-dir

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: install dependencies
      run: |
        echo 'deb http://www.cs.ox.ac.uk/chaste/ubuntu focal/' | sudo tee -a /etc/apt/sources.list.d/chaste.list
        sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 422C4D99
        sudo apt update
        sudo apt install chaste-dependencies

    - name: cache build directory
      uses: actions/cache@v2
      id: cache
      with:
        path: chaste-build-dir
        key: ${{ runner.os }}-${{ hashFiles('docs/ReleaseNotes.html') }}

    - name: make build and test directories
      run: |
        mkdir -p chaste-build-dir
        mkdir -p ${CHASTE_TEST_OUTPUT}

    - name: make test directory
      run: mkdir chaste-test-dir

    - name: cmake configure
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
      working-directory: chaste-build-dir

    - name: build core libraries
      run: cmake --build . --parallel 2 --target chaste_core
      working-directory: chaste-build-dir

    - name: build cell_based
      run: cmake --build . --parallel 2 --target chaste_cell_based
      working-directory: chaste-build-dir

    - name: build crypt
      run: cmake --build . --parallel 2 --target chaste_crypt
      working-directory: chaste-build-dir

    - name: build heart
      run: cmake --build . --parallel 2 --target chaste_heart
      working-directory: chaste-build-dir

    - name: build lung
      run: cmake --build . --parallel 2 --target chaste_lung
      working-directory: chaste-build-dir

    - name: build continuous test pack
      run: cmake --build . --parallel 2 --target Continuous
      working-directory: chaste-build-dir

    - name: build nightly test pack
      run: cmake --build . --parallel 2 --target Nightly
      working-directory: chaste-build-dir

    - name: run Continuous test pack
      run: ctest -j2 -L Continuous --output-on-failure
      working-directory: chaste-build-dir

    - name: run Nightly test pack
      run: ctest -j2 -L Nightly --output-on-failure
      working-directory: chaste-build-dir
